version: '3.8'
services:
  # MYSQL
  mysql-db:
    build: ./mysql
    image: ${DB_IMG}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - .env
    container_name: ${DB_CONTAINER}
    ports:
        - "3306:3306"
    restart: always

  # APP
  gecko-app:
    build: ./gecko
    image: ${APP_IMG}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    container_name: ${APP_CONTAINER}
    ports:
        - "7000:7000"
    restart: always
    depends_on:
      - mysql-db
