management:
  endpoints:
    web:
      exposure:
        include: "info"

spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:devDB"
    username: "sa"
    password: ""

server:
  port: 8081